<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { BaseImages, Convert, CreateVM, DeleteVM, Health, Images, MetricsStream, Operations, RuntimeStatus, SetAuthToken, VMAction, VMs } from './api'

const tabs = [
  { id: 'overview', label: 'Dashboard', icon: '⌂' },
  { id: 'convert', label: 'Convert', icon: '⇄' },
  { id: 'vms', label: 'Workloads', icon: '▣' },
  { id: 'images', label: 'Images', icon: '◈' },
]
const state = reactive({ tab: 'overview', token: localStorage.getItem('firecracker-studio.api-token') || '', source: 'alpine:latest', sourceType: 'oci', baseProfile: 'alpine', vcpus: 1, memoryMiB: 512, hostPort: 15432, guestPort: 5432, protocol: 'tcp', selectedVM: '' })
const data = reactive({ health: null, runtime: {}, metrics: { microvms: 0, runningVms: 0, images: 0, operations: 0, host: {} }, vms: [], images: [], baseImages: [], operations: [], message: '' })
const busy = ref(false)
let metricsSource
let refreshTimer
const selectedVM = computed(() => data.vms.find(vm => vm.id === state.selectedVM) || data.vms[0] || null)
const latestOperation = computed(() => data.operations.slice().sort((a, b) => new Date(b.updatedAt || b.createdAt) - new Date(a.updatedAt || a.createdAt))[0] || null)
const runtimeReady = computed(() => data.runtime.ready === true)
function formatBytes(value = 0) { if (!value) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const index = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); return `${(value / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}` }
function errorText(error) { return String(error).replace(/^Error: /, '') }
function selectTab(tab) { state.tab = tab }
function startMetrics() { metricsSource?.close(); metricsSource = MetricsStream(metrics => { data.metrics = metrics }, () => {}) }
function saveToken() { SetAuthToken(state.token); data.message = state.token ? 'API token saved in this browser' : 'API token cleared'; startMetrics(); refresh() }
async function refresh() {
  try {
    data.runtime = await RuntimeStatus(); data.health = await Health()
    const [vms, images, baseImages, operations] = await Promise.all([VMs(), Images(), BaseImages(), Operations()])
    data.vms = vms.vms || []; data.images = images.images || []; data.baseImages = baseImages.images || []; data.operations = operations.operations || []
    if (!state.selectedVM && data.vms[0]) state.selectedVM = data.vms[0].id
  } catch (error) { data.health = null; data.message = errorText(error) }
}
async function convert() { busy.value = true; try { const operation = await Convert(state.source, state.sourceType, state.baseProfile); data.message = `Conversion queued: ${operation.id}`; state.tab = 'convert'; await refresh() } catch (error) { data.message = errorText(error) } finally { busy.value = false } }
async function createVM() {
  if (!latestOperation.value?.artifact?.digest) { data.message = 'Wait for a successful conversion before creating a workload'; return }
  busy.value = true
  try { const vm = await CreateVM(latestOperation.value.artifact.digest, Number(state.vcpus), Number(state.memoryMiB), latestOperation.value.request.source, [{ hostPort: Number(state.hostPort), guestPort: Number(state.guestPort), protocol: state.protocol }]); state.selectedVM = vm.id; state.tab = 'vms'; data.message = 'Workload created. Press Start when ready.'; await refresh() } catch (error) { data.message = errorText(error) } finally { busy.value = false }
}
async function vmAction(id, action) { busy.value = true; try { await VMAction(id, action); data.message = `Workload ${action} requested`; await refresh() } catch (error) { data.message = errorText(error) } finally { busy.value = false } }
async function deleteVM(id) { if (!window.confirm('Delete this microVM and its managed files?')) return; busy.value = true; try { await DeleteVM(id); state.selectedVM = ''; data.message = 'Workload deleted'; await refresh() } catch (error) { data.message = errorText(error) } finally { busy.value = false } }
onMounted(async () => { SetAuthToken(state.token); startMetrics(); await refresh(); refreshTimer = window.setInterval(() => { if (state.tab === 'vms' || state.tab === 'convert') refresh() }, 4000) })
onBeforeUnmount(() => { metricsSource?.close(); if (refreshTimer) window.clearInterval(refreshTimer) })
</script>

<template>
  <div class="app-shell">
    <aside class="sidebar"><div class="brand"><span class="brand-mark">F</span><div><strong>Firecracker Studio</strong><small>microVM control</small></div></div><div class="connection-card"><span class="status-dot" :class="{ online: data.health }"></span><div><strong>{{ data.health ? 'Connected' : 'Offline' }}</strong><small>{{ runtimeReady ? 'Runtime ready' : 'Check readiness' }}</small></div></div><nav><button v-for="tab in tabs" :key="tab.id" :class="{ active: state.tab === tab.id }" @click="selectTab(tab.id)"><span>{{ tab.icon }}</span>{{ tab.label }}<b v-if="tab.id === 'vms' && data.vms.length">{{ data.vms.length }}</b></button></nav><div class="sidebar-foot">v1.4.2 · local control server</div></aside>
    <main class="main"><header class="topbar"><div><small class="overline">{{ tabs.find(tab => tab.id === state.tab)?.label }}</small><h1>{{ state.tab === 'overview' ? 'Workspace' : tabs.find(tab => tab.id === state.tab)?.label }}</h1></div><div class="token-box"><input v-model="state.token" type="password" placeholder="API token (optional)" @keyup.enter="saveToken" /><button class="button subtle" @click="saveToken">Save</button></div></header><div v-if="data.message" class="notice" role="status">{{ data.message }}</div>
      <section v-if="state.tab === 'overview'" class="view"><div class="hero"><div><small class="overline">LOCAL FIRECRACKER CONTROL</small><h2>Run microVMs without the socket work.</h2><p>Studio controls the Firecracker runtime already installed on this host.</p></div><button class="button primary" @click="selectTab('convert')">Convert an image</button></div><div class="stat-grid"><div class="stat"><small>MicroVMs</small><strong>{{ data.metrics.microvms }}</strong><span>{{ data.metrics.runningVms }} running</span></div><div class="stat"><small>Images</small><strong>{{ data.metrics.images }}</strong><span>local artifacts</span></div><div class="stat"><small>Operations</small><strong>{{ data.metrics.operations }}</strong><span>conversion jobs</span></div><div class="stat"><small>Runtime</small><strong>{{ runtimeReady ? 'Ready' : 'Check' }}</strong><span>{{ data.runtime.message || 'status unavailable' }}</span></div></div><div class="two-column"><article class="card"><div class="card-heading"><div><small class="overline">FIRST RUN</small><h3>Host readiness</h3></div><span class="badge" :class="runtimeReady ? 'good' : 'warn'">{{ runtimeReady ? 'Ready' : 'Needs attention' }}</span></div><div class="check-list"><div><span>Firecracker</span><b>{{ data.runtime.installed ? 'Installed' : 'Missing' }}</b></div><div><span>KVM</span><b>{{ data.runtime.kvm || 'Unknown' }}</b></div><div><span>Kernel</span><b>{{ data.runtime.kernel || 'Unknown' }}</b></div><div><span>Rootfs</span><b>{{ data.runtime.rootfs || 'Unknown' }}</b></div></div><p class="hint">Install the runtime separately. Studio never hides a missing prerequisite.</p></article><article class="card"><div class="card-heading"><div><small class="overline">RECENT</small><h3>Workloads</h3></div><button class="button subtle" @click="selectTab('vms')">View all</button></div><div v-if="data.vms.length" class="compact-list"><button v-for="vm in data.vms.slice(0, 4)" :key="vm.id" class="list-row" @click="state.selectedVM = vm.id; selectTab('vms')"><span class="list-icon">▣</span><span><strong>{{ vm.id.slice(0, 12) }}</strong><small>{{ vm.imageReference || vm.artifactDigest }}</small></span><span class="badge" :class="vm.state">{{ vm.state }}</span></button></div><div v-else class="empty">No workloads yet.</div></article></div></section>
      <section v-else-if="state.tab === 'convert'" class="view narrow"><div class="page-intro"><small class="overline">IMAGE WORKFLOW</small><h2>Convert an image</h2><p>Turn an OCI image into a local Firecracker artifact.</p></div><article class="card form-card"><label>Image reference<input v-model="state.source" placeholder="alpine:latest" /></label><div class="form-grid"><label>Source<select v-model="state.sourceType"><option value="oci">OCI / Docker image</option><option value="dockerfile">Dockerfile</option><option value="archive">OCI archive</option></select></label><label>Base profile<select v-model="state.baseProfile"><option>alpine</option><option>debian</option><option>ubuntu</option></select></label></div><button class="button primary wide" :disabled="busy || !state.source" @click="convert">{{ busy ? 'Converting…' : 'Start conversion' }}</button></article><article class="card"><div class="card-heading"><div><small class="overline">BUILD HISTORY</small><h3>Operations</h3></div><span v-if="latestOperation" class="badge" :class="latestOperation.state">{{ latestOperation.state }}</span></div><div v-if="latestOperation" class="operation-detail"><div class="detail-line"><span>Source</span><strong>{{ latestOperation.request.source }}</strong></div><div class="detail-line"><span>Digest</span><strong class="mono">{{ latestOperation.artifact?.digest || 'pending' }}</strong></div><pre>{{ (latestOperation.logs || []).join('\n') }}{{ latestOperation.error ? '\n' + latestOperation.error : '' }}</pre><button v-if="latestOperation.state === 'succeeded'" class="button primary wide" @click="createVM">Create workload</button></div><div v-else class="empty">No conversion operations yet.</div></article></section>
      <section v-else-if="state.tab === 'vms'" class="view"><div class="page-intro row"><div><small class="overline">LOCAL WORKLOADS</small><h2>Workloads</h2><p>Start, stop, inspect, or remove your microVMs.</p></div><button class="button primary" @click="selectTab('convert')">Create workload</button></div><div class="workload-layout"><article class="card workload-list"><div v-if="data.vms.length" class="compact-list"><button v-for="vm in data.vms" :key="vm.id" class="list-row" :class="{ selected: selectedVM?.id === vm.id }" @click="state.selectedVM = vm.id"><span class="list-icon">▣</span><span><strong>{{ vm.id.slice(0, 12) }}</strong><small>{{ vm.imageReference || vm.artifactDigest }}</small></span><span class="badge" :class="vm.state">{{ vm.state }}</span></button></div><div v-else class="empty">No workloads yet. Convert an image to begin.</div></article><article v-if="selectedVM" class="detail-stack"><div class="card detail-header"><div><small class="overline">MICROVM</small><h3>{{ selectedVM.id.slice(0, 12) }}</h3><p>{{ selectedVM.state }} · updated {{ new Date(selectedVM.updatedAt).toLocaleString() }}</p></div><div class="action-row"><button class="button primary" :disabled="busy || selectedVM.state === 'running'" @click="vmAction(selectedVM.id, 'start')">Start</button><button class="button subtle" :disabled="busy || selectedVM.state !== 'running'" @click="vmAction(selectedVM.id, 'stop')">Stop</button><button class="button danger" :disabled="busy" @click="deleteVM(selectedVM.id)">Delete</button></div></div><div class="card"><div class="card-heading"><h3>Details</h3><span class="badge" :class="selectedVM.state">{{ selectedVM.state }}</span></div><div class="detail-grid"><div><small>Image</small><strong>{{ selectedVM.imageReference || 'Unnamed image' }}</strong></div><div><small>Artifact</small><strong class="mono">{{ selectedVM.artifactDigest }}</strong></div><div><small>Published ports</small><strong>{{ selectedVM.portMappings?.length || 0 }}</strong></div></div></div><div class="card"><div class="card-heading"><h3>Studio lifecycle events</h3></div><pre class="logs">{{ selectedVM.logs?.join('\n') || 'No lifecycle events yet.' }}</pre></div></article><div v-else class="card empty large">Select a workload to inspect it.</div></div></section>
      <section v-else class="view"><div class="page-intro"><small class="overline">LOCAL ARTIFACTS</small><h2>Images</h2><p>Artifacts created by your conversions.</p></div><article class="card"><div v-if="data.images.length" class="compact-list"><div v-for="image in data.images" :key="image.digest" class="list-row static"><span class="list-icon">◈</span><span><strong>{{ image.reference }}</strong><small class="mono">{{ image.digest }}</small></span><span class="badge good">ready</span></div></div><div v-else class="empty">No local images yet. Convert an image to create one.</div></article><article class="card"><div class="card-heading"><h3>Runtime assets</h3><span class="badge">{{ data.baseImages.length }}</span></div><p class="hint">Firecracker runtime installation is separate from Studio. These entries describe host assets available to the server.</p><div v-if="data.baseImages.length" class="compact-list"><div v-for="image in data.baseImages" :key="image.id" class="list-row static"><span class="list-icon">◇</span><span><strong>{{ image.name || image.id }}</strong><small>{{ image.distribution || 'Firecracker' }} · {{ image.architecture || 'native' }}</small></span></div></div></article></section>
    </main>
  </div>
</template>
