// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connection():Promise<{[key: string]: string}>;

export function Convert(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: any}>;

export function CreateVM(arg1:string,arg2:number,arg3:number):Promise<{[key: string]: any}>;

export function Health():Promise<{[key: string]: any}>;

export function Images():Promise<{[key: string]: any}>;

export function Operations():Promise<{[key: string]: any}>;

export function SetConnection(arg1:string,arg2:string):Promise<void>;

export function Snapshot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<{[key: string]: any}>;

export function VMAction(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function VMs():Promise<{[key: string]: any}>;
