// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3, arg4, arg5);
}

export function BaseImages() {
  return window['go']['main']['App']['BaseImages']();
}

export function CheckServer(arg1) {
  return window['go']['main']['App']['CheckServer'](arg1);
}

export function Connection() {
  return window['go']['main']['App']['Connection']();
}

export function Convert(arg1, arg2, arg3) {
  return window['go']['main']['App']['Convert'](arg1, arg2, arg3);
}

export function CreateVM(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateVM'](arg1, arg2, arg3);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function Images() {
  return window['go']['main']['App']['Images']();
}

export function Operations() {
  return window['go']['main']['App']['Operations']();
}

export function Servers() {
  return window['go']['main']['App']['Servers']();
}

export function SetConnection(arg1, arg2) {
  return window['go']['main']['App']['SetConnection'](arg1, arg2);
}

export function Snapshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Snapshot'](arg1, arg2, arg3, arg4);
}

export function SwitchServer(arg1) {
  return window['go']['main']['App']['SwitchServer'](arg1);
}

export function VMAction(arg1, arg2) {
  return window['go']['main']['App']['VMAction'](arg1, arg2);
}

export function VMs() {
  return window['go']['main']['App']['VMs']();
}
