// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';

export function Accounts():Promise<Array<connections.Account>>;

export function AddAccount(arg1:string,arg2:string):Promise<connections.Account>;

export function AddServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<connections.Server>;

export function BaseImages():Promise<{[key: string]: any}>;

export function CheckServer(arg1:string):Promise<connections.Server>;

export function Connection():Promise<{[key: string]: string}>;

export function Convert(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: any}>;

export function CreateVM(arg1:string,arg2:number,arg3:number):Promise<{[key: string]: any}>;

export function Health():Promise<{[key: string]: any}>;

export function Images():Promise<{[key: string]: any}>;

export function Operations():Promise<{[key: string]: any}>;

export function Servers():Promise<Array<connections.Server>>;

export function SetConnection(arg1:string,arg2:string):Promise<void>;

export function Snapshot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<{[key: string]: any}>;

export function SwitchServer(arg1:string):Promise<connections.Server>;

export function VMAction(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function VMs():Promise<{[key: string]: any}>;
